### ISSUE TITLE
Request: Update plugin for 0.85.x

### ISSUE THREAD

**Issue by PHiAX** [TECLIB/genericobject#10]
Any plans for upgrading this plugin for GLPI 0.85.x?

**Comment by wawax** [comment]
Hello,

Yes we plan to finish the port but we have no due date for the moment.

**Comment by nqb** [comment]
Hello,

What are last things to do ? How to help you ?

Could you tell us if plugin will be support for future major versions of GLPI (0.86, 0.87, etc.) ?

**Comment by wawax** [comment]
Hello,

Migration from 0.84 has not yet been coded and the plugin has not been heavily tested.
At a community level I don't know when the plugin be available, and for which version of GLPI.

For more information, you can contact teclib' (contact@teclib.com) for professional support.

**Comment by mag3nt** [comment]
Hello,
this plugin is heavily used by me and my colleagues, please let me know if there is anything we can do to help and if you're planning to keep updating the plugin for future releases.

Thanks

**Comment by wawax** [comment]
Hello,

You can the test 0.85/work branch. The only thing that is not yet functionnaly should be profile migration.
We have no release date right now, and plan to work on it in the coming weeks.

**Comment by mag3nt** [comment]
Hello,
Thanks for the informations.

We have deployed and tested the 0.85 branch and everything seems to work fine (limited to the subset of funcionalities we use).

Thank you so much!

-------------------------------
Maurizio Gentile

**Comment by PHiAX** [comment]
Hi,

We've just installed the plugin and everything seems to work fine.
Thank you!

**Comment by wawax** [comment]
The plugin's update process has been coded.
The plugin works in 0.85 and upcoming 0.90
