### ISSUE TITLE
Droits de configuration trop larges

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/genericobject#11]
Il semble que les droits de CONFIGURATION du plugin soient implicitement accordés à TOUS les profils qui ne soient pas de type Self-Service.
Ce qui fait beaucoup.

**Comment by wawax** [comment]
Je n'arrive pas à reproduire avec le code actuel, en testant avec un profil Admin ou Hotliner

**Comment by blerohellec** [comment]
En effet, avec la version 2.4.1 pour 0.85, c'est maintenant correctement géré.
Les droits de configuration sont explicitement gérés, et seul le Super-Admin a des droits de configuration, à l'installation.
