### ISSUE TITLE
PHP errors in Debug Tab

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/genericobject#12]
Version 2.3.2 for GLPI 0.84
While in Debut Mode, if the object is authorized for reservations (available or not), going to the Debug Tab generates php errors. Extract hereafter.
Nevertheless, the result on screen (notifications) seems to be correct.

2015-04-13 14:43:13
Notice(8): Undefined index: entities_id
Backtrace :
/var/www/glpi084/inc/toolbox.class.php:531              Toolbox::userErrorHandlerNormal()
/var/www/glpi084/inc/notificationtargetreservation.class.php:111                Toolbox::userErrorHandlerDebug()
/var/www/glpi084/inc/notificationtarget.class.php:1072          NotificationTargetReservation->getDatasForTemplate()
/var/www/glpi084/inc/notificationtemplate.class.php:227         NotificationTarget->getForTemplate()
/var/www/glpi084/inc/notificationevent.class.php:163            NotificationTemplate->getTemplateByLanguage()
/var/www/glpi084/inc/notificationevent.class.php:220            NotificationEvent::raiseEvent()
/var/www/glpi084/inc/reservationitem.class.php:526              NotificationEvent::debugEvent()
/var/www/glpi084/inc/commonglpi.class.php:618           ReservationItem->showDebugResa()
/var/www/glpi084/inc/commonglpi.class.php:270           CommonGLPI->showDebugInfo()
/var/www/glpi084/ajax/common.tabs.php:71                CommonGLPI::displayStandardTab()

2015-04-13 14:43:13
Notice(8): Undefined index: items
Backtrace :
/var/www/glpi084/inc/toolbox.class.php:531              Toolbox::userErrorHandlerNormal()
/var/www/glpi084/inc/notificationtargetreservation.class.php:113                Toolbox::userErrorHandlerDebug()
/var/www/glpi084/inc/notificationtarget.class.php:1072          NotificationTargetReservation->getDatasForTemplate()
/var/www/glpi084/inc/notificationtemplate.class.php:227         NotificationTarget->getForTemplate()
/var/www/glpi084/inc/notificationevent.class.php:163            NotificationTemplate->getTemplateByLanguage()
/var/www/glpi084/inc/notificationevent.class.php:220            NotificationEvent::raiseEvent()
/var/www/glpi084/inc/reservationitem.class.php:526              NotificationEvent::debugEvent()
/var/www/glpi084/inc/commonglpi.class.php:618           ReservationItem->showDebugResa()
/var/www/glpi084/inc/commonglpi.class.php:270           CommonGLPI->showDebugInfo()
/var/www/glpi084/ajax/common.tabs.php:71                CommonGLPI::displayStandardTab()

2015-04-13 14:43:13
Warning(2): Invalid argument supplied for foreach()
Backtrace :
/var/www/glpi084/inc/toolbox.class.php:531              Toolbox::userErrorHandlerNormal()
/var/www/glpi084/inc/notificationtargetreservation.class.php:113                Toolbox::userErrorHandlerDebug()
/var/www/glpi084/inc/notificationtarget.class.php:1072          NotificationTargetReservation->getDatasForTemplate()
/var/www/glpi084/inc/notificationtemplate.class.php:227         NotificationTarget->getForTemplate()
/var/www/glpi084/inc/notificationevent.class.php:163            NotificationTemplate->getTemplateByLanguage()
/var/www/glpi084/inc/notificationevent.class.php:220            NotificationEvent::raiseEvent()
/var/www/glpi084/inc/reservationitem.class.php:526              NotificationEvent::debugEvent()
/var/www/glpi084/inc/commonglpi.class.php:618           ReservationItem->showDebugResa()
/var/www/glpi084/inc/commonglpi.class.php:270           CommonGLPI->showDebugInfo()
/var/www/glpi084/ajax/common.tabs.php:71                CommonGLPI::displayStandardTab()

**Comment by neeftarah** [comment]
Not reproduced
