### ISSUE TITLE
 Objects management 2.4.0 can`t switch to child entity

### ISSUE THREAD

**Issue by shercargo** [TECLIB/genericobject#17]
We use GLPI 0.85.4 & one entity with a one child entity. After installing Objects management 2.4.0. and enabling it, we cant choose a child entity.

**Comment by neeftarah** [comment]
NB : the 2.4.0 version was unstable and shouldn't has been created. It has been removed immediately.
Congratulation, you have been very fast to take it.
Thanks for your help identifying those very important bugs, but, please, consider you use a development version.

**Comment by shercargo** [comment]
Thank you for detailed explanation. If some help with testing needed - we ready!

**Comment by wawax** [comment]
please test with the latest snapshot

**Comment by wawax** [comment]
bug reproduced, will be fixed in next release
