### ISSUE TITLE
2.4.0 - 0.85 Unable to link custom object to ticket call

### ISSUE THREAD

**Issue by dcanalia** [TECLIB/genericobject#19]
Hi, i have create some new item categories and i have add there my items.
I can upload document, assign elements to a user, but i cannot add to the new items of those categories any ticket call
As you can see in the image attached, the combobox of the ticket only show "core categories"

Can you help me please?
![glpi_cattura01](https://cloud.githubusercontent.com/assets/13151227/8477735/b88c5316-20cc-11e5-9c50-7ea13c3cde5d.GIF)
![glpi_cattura02_assets](https://cloud.githubusercontent.com/assets/13151227/8477736/b894958a-20cc-11e5-81f1-eeb24e32d4ec.GIF)

**Comment by jmreymond** [comment]
Go to Administration/Profiles, select a profile and then Go to Assistance/Association/Associable items to a ticket.
Click in the box and you have the choice to select the GLPI objects

**Comment by wawax** [comment]
jmreymond's answer is correct
