### ISSUE TITLE
GLPI 0.8.5 URL générée incorrecte

### ISSUE THREAD

**Issue by jmreymond** [TECLIB/genericobject#22]
On crée un objet puis une instance de l'objet
On crée un contrat qu'on associe à cet objet
Quand on liste ce contrat et qu'on va sur Elements, on retrouve notre objet.
Si on clique sur l'objet, on a le message (pour un batiment)
The requested URL /plugins/genericobject/front/batiment.form.php was not found on this server.
alors qu'on devrait générer
/plugins/genericobject/front/object.form.php?itemtype=PluginGenericobjectBatiment&id=1

**Comment by wawax** [comment]
Sera corrigé en 0.90, nécessite une modification du coeur de GLPI

**Comment by wawax** [comment]
A retester avec mes derniers commits et le dernier snapshot de la 0.90

**Comment by wawax** [comment]
fixed in 0.90
