### ISSUE TITLE
GLPI 0.8.5 Erreur sur champ personnalisé

### ISSUE THREAD

**Issue by jmreymond** [TECLIB/genericobject#23]
En créant un champ personnalisé comme suit:
$GO_FIELDS['ckr_ident']['name']       = 'Courriel';
$GO_FIELDS['ckr_ident']['input_type'] = 'text';

l'utilisation de ce champ amène des pages blanches
remplacer ckr_ident par ckr_identification ne change rien
remplacer ckr_ident par ckrident résout le soucis
manifestement, ce qui est avant _ n'est pas pris en compte et on entre en collision avec des mots clefs protégés (qu'on ne connait pas)

**Comment by wawax** [comment]
en fait on testait si on trouvait _id dans le nom du champ. Si oui alors on estimait que c'était une dropdown

**Comment by wawax** [comment]
A retester avec mes derniers commits

**Comment by jmreymond** [comment]
corrigé en 0.85

**Comment by jmreymond** [comment]
j'ai comme l'impression qu'il y a quand me un blême.
Avec
$GO_FIELDS['ckr_cptilles_id']['name']='Gerard';
$GO_FIELDS['ckr_cptilles_id']['field']='cptille';
$GO_FIELDS['ckr_cptilles_id']['input_type']='dropdown';

j'ai une table mysql qui s'appelle, glpi_plugin_genericobject_ckrs_cptilles et donc, impossible de rajouter un élément
Si je supprime le ckr_ au profit de 
$GO_FIELDS['cptilles_id']['name']='Gerard';
$GO_FIELDS['cptilles_id']['field']='cptille';
$GO_FIELDS['cptilles_id']['input_type']='dropdown';
la table s'appelle glpi_plugin_genericobject_cptilles et tout fonctionne
