### ISSUE TITLE
GLPI 0.8.5 Impossible de créer un objet avec des caractères accentués

### ISSUE THREAD

**Issue by jmreymond** [TECLIB/genericobject#27]
Quand on crée un objet, on ne peut pas modifier son libellé qui est directement issu de l'identifiant. Ainsi, si on crée musée, il transforme l’identifiant en musee (why not ?) et surtout le libellé en Musee. On perd donc l'accent et il faut aller dans la base mysql pour changer le nom.

**Comment by wawax** [comment]
Bonsoir,

C'est normal, le libellé n'est pas éditable depuis l'interface, il faut éditer le fichier dans glpi/files/_plugins/genericobject/locales/musee/musee.fr_FR.php

**Comment by jmreymond** [comment]
Cela fonctionne mais il serait préférable de prendre tel quel le libellé sans lui appliquer une transformation consistant à mettre chaque début de mot en majuscule.
