### ISSUE TITLE
GLPI 0.8.5 Erreur sur le changement du nombre d'items affichés

### ISSUE THREAD

**Issue by jmreymond** [TECLIB/genericobject#29]
Avec un profil super-admin, quand on va dans configuration/Intitulés/Gestion d'objets, on prend un des dropdown proposé et il s'affiche. Si dans la liste déroulante "Affichage (nombre d'éléments) ", on essaie de changer de 20 à 50 (par exemple), on a le message suivant
The requested dropdown does not exists
parfois, on a le même message mais en français
L'action que vous avez réalisée n'est pas autorisée.

/plugins/genericobject/front/commondropdown.php?itemtype=PluginGenericobjectCkrbatitype?sort=1&order=ASC&criteria[0][field]=view&criteria[0][link]=contains&criteria[0][value]=&&start=0

**Comment by jmreymond** [comment]
idem, si pour un objet, on liste toutes les instances de cet objet. Changer le nombre d'éléments affichés provoque l'affichage d'une page quasiment blanche

**Comment by wawax** [comment]
Merci de tester le dernier snapshot du plugin avec le dernier snapshot glpi 0.90

**Comment by jmreymond** [comment]
corrigé avec les dernières versions de glpi et de GO
