### ISSUE TITLE
GLPI 0.8.5 Erreur sur la liste des contrats associables à un objet

### ISSUE THREAD

**Issue by jmreymond** [TECLIB/genericobject#30]
Dans la liste déroulante des contrats associables à un objet, on retrouve un contrat déjà associé.
Associer un autre contrat à cet objet fait disparaître la précédente entrée de la liste mais le dernier contrant ajouté est présent dans la liste déroulante.
Si on sélectionne un contrat déjà associé, l'action Ajouter ne fait rien ce qui est normal

**Comment by wawax** [comment]
Bonsoir,

Est-ce que le contrat peut bien contenir plus d'un élément ?

**Comment by jmreymond** [comment]
oui, positionné à illimité

**Comment by wawax** [comment]
quelle version de glpi et du plugin utilises-tu ?

**Comment by jmreymond** [comment]
glpi 0.85 et le plugin GO en version 0.85-2.4.0

**Comment by wawax** [comment]
désolé mais je ne reproduis absolument pas ce bug.
j'aimerai bien une capture d'écran sur une 0.90 récente.

**Comment by jmreymond** [comment]
tout est ok avec la 0.90 RC1 et la dernière version de genericobject
