### ISSUE TITLE
GLPI 0.8.5 Lien erroné dans la liste des matériels d'un ticket et d'un contrat

### ISSUE THREAD

**Issue by jmreymond** [TECLIB/genericobject#31]
Dans le cadre d'un ticket, on associe un objet. Quand on va dans l'onglet  Eléments du ticket, on retrouve bien l'objet. Si on clique sur l'hyperlien correspondant à l'objet, on obtient une erreur 404
The requested URL /plugins/genericobject/front/batiment.form.php was not found on this server.

La syntaxe correcte doit être
/plugins/genericobject/front/object.form.php?itemtype=PluginGenericobjectPiscine&id=2

**Comment by jmreymond** [comment]
idem pour un contrat. Si on va dans l'onglet Elements du contrat, on a la même erreur 404
The requested URL /plugins/genericobject/front/batiment.form.php was not found on this server.

**Comment by wawax** [comment]
Problème du coeur de GLPI. Sera fixé en 0.90
