### ISSUE TITLE
Search in tickets problems

### ISSUE THREAD

**Issue by jbaojunior** [TECLIB/genericobject#32]
Hi,
I have problems when loading a bookmark with your plugin enabled. It doesn't happens with it disabled.

I can't perform any search when I have a default view marked in bookmarks. Whenever I click  the search button with a new search it aways reload my default search and I can't perform a new one.

Loading another bookmark work until I change pages. Clicking in menu again, the search is lost.

I'm using the lastest version of genericobject and GLPI 0.85.4.

Thanks.

**Comment by wawax** [comment]
Hi,

I do not reproduce the bug.
Please give me : 
* an example of bookmark
* any red message appearing in debug mode (in your preferences, run GLPI in debug mode)
* any message appearing in GLPI's logfiles (glpi/fles/_log/php-errors.log and glpi/files/_log/sql_errors.log)

**Comment by jbaojunior** [comment]
Wawax,

By debugging I realized that the function below in profile.class.php causes my problem:

   public static function reloadProfileRights() {
      if (isset($_SESSION['glpiactiveprofile']['id'])) {
         Session::changeProfile($_SESSION['glpiactiveprofile']['id']);
      }
   }

Whenever I execute my search, the function reload  my profile that reloads my default bookmark..
I have migrate from GLPI 0.84 to 0.85.

Wouldn't that profile reload be only to search in plugin? I can safely comment out that function line that reloads the profile as a workaround?

**Comment by wawax** [comment]
Please test with the latest snapshot.
I've fixed the problem, the plugin was resetting the session at each page load...

**Comment by wawax** [comment]
closed with last commits
