### ISSUE TITLE
GLPI 0.8.5 Affichage incomplet des entités rattachées à un contrat

### ISSUE THREAD

**Issue by jmreymond** [TECLIB/genericobject#35]
Pour un contrat, on  a plusieurs entités associés. Dans la colonne Type, pour les trois lignes correspondant aux trois éléments, seule une ligne est renseignée. Elle semble correspondre systématiquement à la plus haute valeur. Par exemple, un objet avec l'Id 4, Id 5 et Id 8, seul l'Id 8 sera affiché. Si je supprime l'association avec l'élément Id 8, ce sera l'Id 5 qui sera affiché
![capture du 2015-07-21 19 54 01](https://cloud.githubusercontent.com/assets/8809413/8808337/43a803fe-2fe2-11e5-9ff5-65b4417a3dfe.png)

**Comment by jmreymond** [comment]
Après suppression de l'association avec l'Id 3
![capture du 2015-07-21 19 57 28](https://cloud.githubusercontent.com/assets/8809413/8808417/c51f0112-2fe2-11e5-9800-ae7363f7e534.png)

**Comment by wawax** [comment]
Désolé mais je ne comprend pas où est le souci.
Tous les objets associés au contrat sont des Bâtiments ?

**Comment by jmreymond** [comment]
oui, tous des batiments et on voit sur la seconde copie d'écran qu'en supprimant Batiment 3, on voit arriver Batiment 2 dans la colonne Type

**Comment by wawax** [comment]
dans la colonne type, le nombre indique le nombre d'élément associés au contrat (ici 3 bâtiments sur la première capture, et 2 pour la seconde)

**Comment by jmreymond** [comment]
OK, c'est clair avec les explications
