### ISSUE TITLE
Status always in French, whatever the GLPI language is

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/genericobject#36]
I'm running 0.85-2.4.1
In English, Spanish... the field status is always named Statut (French, not translated).
Check add a field to object, view of the object....

**Comment by blerohellec** [comment]
Also, in the Fields tab of an object type, in the list of fields to add, for Domain, Group... Isolated is used (always in English)

**Comment by wawax** [comment]
Hi Benoît,
I don't reproduce the issue on GLPI 0.90...

Could you put one or two screenshots ? Thanks

**Comment by blerohellec** [comment]
Indeed, in 0.85, Status is translated into the current language -> OK
But "Isolated" still remains in english.

**Comment by blerohellec** [comment]
Error in previous post.
Indeed, in 0.90, Status is translated into the current language -> OK
But "Isolated" still remains in english.

**Comment by blerohellec** [comment]
OK. "Isolated" no longer displayed
