### ISSUE TITLE
Pour un type d'objet, non prise en compte de l'entité

### ISSUE THREAD

**Issue by jmreymond** [TECLIB/genericobject#37]
Avec un profil appartenant à une entité, on liste les profils attachés à un type d'objet. On retrouve tous les profils, y compris ceux qui sont dans une autre entité, complètement distincte et étanche.

**Comment by wawax** [comment]
Bonsoir Jean-Max,

les profils ne sont pas associés à des entités, tout comme les types d'objets.
dans ce que tu décrits, je ne vois rien d'anormal à cela.

je veux bien une capture d'écran pour comprendre.

**Comment by jmreymond** [comment]
l'utilisateur est dans l'entité cagnes, appartient au profil cagnes_direction et ne connait rien d'autres entités en parallèle. Avec la copie d'écran, on s’aperçoit qu'il voit une entité lepontet qui n'appartient pas à son entité

![capture du 2015-08-16 09 32 06](https://cloud.githubusercontent.com/assets/8809413/9292449/ce833ffe-43f9-11e5-81e6-a9106d42b55b.png)

**Comment by wawax** [comment]
l'utilisateur a droit de voir et modifier les profils ?

**Comment by jmreymond** [comment]
oui, mais  uniquement  pour son entité (c'est l'admin de Cagnes) et cela fonctionne bien ainsi.

![capture du 2015-08-16 11 38 16](https://cloud.githubusercontent.com/assets/8809413/9292782/5f96105a-440b-11e5-828d-2afac3453957.png)

**Comment by jmreymond** [comment]
on s’aperçoit également qu'une personne ayant le profil cagnes_direction peut rajouter ou supprimer un champ alors qu'elle n'a aucun droit sur cet objet, cf première copie d'écran

**Comment by jmreymond** [comment]
il me semble qu'on a le même problème de fond avec le core glpi qui n'étanchéifie pas les profils.

**Comment by wawax** [comment]
oui c'est ce que je dis depuis mon premier suivi, les profils sont globaux et donc non soumis à filtrage par entité.
Donc ce que tu remontes n'est pas un bug à mon avis.

**Comment by jmreymond** [comment]
c'est sans doute un bug mais général à glpi. 
Pour le plugin GO, on est quand même dans une situation où le profil ne dispose d'aucun droit sur un objet et pourtant, il peut tout faire (voir la copie d'écran 1 faite avec un profil cagnes_direction) ce qui semble très étrange

**Comment by wawax** [comment]
Bonjour Jean-Max,

Ce n'est pas spécifique à Genericobject mais un comportement standard de GLPi.
Nous n'allons pas faire de spécifique dans le plugin.

Je ferme le ticket.
Cordialement,
