### ISSUE TITLE
0.90 : impossible to add a field

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/genericobject#39]
v 0.85-1.0 for GLPI 0.90
Now impossible to add a field to an object type : Fatal error: Class 'PluginGeninventorynumberConfigField' not found in /var/www/glpi090/plugins/genericobject/inc/object.class.php on line 172
I don't have the plugin GenInventoryNumber installed.

**Comment by wawax** [comment]
yes it comes from my latest commits.
I'll fix it soon, I've found a better method

**Comment by blerohellec** [comment]
OK. Thx
