### ISSUE TITLE
GLPI 0.85 Mauvais affichage de Utilisateur et Responsable technique

### ISSUE THREAD

**Issue by jmreymond** [TECLIB/genericobject#40]
L'affichage dans liste déroulante Utilisateur et dans Responsable technique ne fait apparaître que l’identifiant
![capture du 2015-08-24 18 20 14](https://cloud.githubusercontent.com/assets/8809413/9445499/cc13907c-4a8c-11e5-9fe7-5154ea6c603e.png)
 de connexion et pas le nom et prénom comme c'est le cas, par exemple, pour un ordinateur.

**Comment by btry** [comment]
Ready to test

**Comment by jmreymond** [comment]
tout fonctionne bien.
merci
