### ISSUE TITLE
GLPI 0.8.5 Bulle à l'affichage d'un objet du parc

### ISSUE THREAD

**Issue by jmreymond** [TECLIB/genericobject#41]
En 0.85 comme en 0.90, si on est dans Parc/Mon Objet, passer la souris sur le nom de l'objet dans la barre horizontale donne une bulle affichant du code html plutôt que le nom de l'objet
![capture du 2015-08-25 15 57 04](https://cloud.githubusercontent.com/assets/8809413/9468448/00edb592-4b42-11e5-9d2b-bfff5c239d05.png)

**Comment by wawax** [comment]
Fermé par suppression de l'icône
