### ISSUE TITLE
Error after creating a value for Category/Model/Type for a genericobjet

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/genericobject#42]
0.90
Given a genericobjet type which has a field Category.
Go to Config > Dropdowns, and create a value for Category. Press Add -> The requested URL /glpi090/plugins/genericobject/front/bicyclettecategory.form.php was not found on this server
Nevertheless, the value is correctly created.

Same for Model & Type

**Comment by btry** [comment]
I do not reproduce, Can you re-check this issue with the latest revision of "master" branch ?

**Comment by blerohellec** [comment]
0.85
I can no longer add a value from Config > Dropdowns > Category (mygenericobject).
The + sign is no longer active.
Please see : https://forge.glpi-project.org/issues/5022

So, I can't say if it's corrected or not.

**Comment by dethegeek** [comment]
Logout from glpi ans log in again. I'll work on this soon.

Le 18 septembre 2015 19:20:23 CEST, blerohellec <notifications@github.com> a écrit :
>0.85
>I can no longer add a value from Config > Dropdowns > Category
>(mygenericobject).
>The + sign is no longer active.
>Please see : https://forge.glpi-project.org/issues/5022
>
>So, I can't say if it's corrected or not.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/TECLIB/genericobject/issues/42#issuecomment-141512361

Cordialement,
Thierry Bugier Pineau

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by blerohellec** [comment]
OK for 0.85 & 0.90

**Comment by btry** [comment]
I fixed (for me) the related. Can you check and report in #52 you no longer need to cycle logout/login ?

**Comment by blerohellec** [comment]
OK. No longer need to logout/in after adding a field to a GO
