### ISSUE TITLE
Empty line in View mngt

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/genericobject#43]
0.90
Given an genericobjet, activated. Open the panel to manage its View, then open the list of fields.
At the beginning of the list, there is an empty line. Generaly, we find here "Characteristics" in bold

**Comment by blerohellec** [comment]
Same in filter panel, where the list behing 'Items seen' has also a blank line.

**Comment by wawax** [comment]
Hello Benoît,

Could you post a screencapture of the problem ?

Thanks in advance,

**Comment by blerohellec** [comment]
Blank line between 'Comments' (1st line, centered) an 'Comments' (3rd line, left padded)
![screenshot from 2015-09-03 16 06 38](https://cloud.githubusercontent.com/assets/9383475/9660436/e712ccd2-5255-11e5-9b29-fa81a0a78284.png)

**Comment by btry** [comment]
I compared the View settings with a core asset. The issue is not the blank line itself, but the lack of the word "Characteristics"

**Comment by blerohellec** [comment]
OK. Thx
