### ISSUE TITLE
Fatal error with disable plugin

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/genericobject#45]
0.90.
install the plugin, activate it. Create a simple genericobject (voiture). Don't even activate it.
Disable the plugin -> 
Fatal error: Class 'PluginGenericobjectObject' not found in /var/www/glpi090/files/_plugins/genericobject/inc/voiture.class.php on line 31

**Comment by wawax** [comment]
Hi Benoît,

Can you test with the latest snapshot ?

Thanks a lot.

**Comment by btry** [comment]
I don't reproduce with the current mater branch.

**Comment by blerohellec** [comment]
It's OK. Thx
