### ISSUE TITLE
Error with Cron

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/genericobject#46]
0.90
I get php errors every time the cron runs.
Stop the cron and error disappears.

  *** PHP Notice(8): Undefined index: glpiactiveprofile
  Backtrace :
  plugins/genericobject/inc/profile.class.php:365    
  plugins/genericobject/setup.php:100                PluginGenericobjectProfile::reloadProfileRights()
  inc/plugin.class.php:128                           plugin_init_genericobject()
  inc/includes.php:133                               Plugin::load()
  front/cron.php:43                                  include()

**Comment by blerohellec** [comment]
Idem when login/logout

**Comment by btry** [comment]
ready to test

**Comment by blerohellec** [comment]
OK. Thx
