### ISSUE TITLE
Ajouter des champs personnalisés à un objet

### ISSUE THREAD

**Issue by matth974** [TECLIB/genericobject#47]
Bonjour,

Nous utilisons la version 0.85-2-4-1 de Generic Objects.

Nous pensons qu'il serait intéressant de permettre l'ajout de champs personnalisés pour chaque objets génériques créés.

Selon le post #23 nous comprenons que cette manipulation reste à priori possible par programmation (à confirmer et à préciser svp). Si tel est le cas, cela suppose qu'à chaque mise à jour du plugin, nous devons recréer nos champs personnalisés?

Merci.
Cordialement

**Comment by wawax** [comment]
Bonjour,

Les champs personnalisés sont définis dans un fichier à part. Lors de la mise à jour, il faut bien penser à remettre ce fichier dans son répertoire.

Nous n'avons pas de plan sur la version actuelle pour remplacer la déclaration en fichier par une déclaration en base de données.

La doc est ici : https://forge.glpi-project.org/projects/genericobject/wiki/20x_En_manual 

Cordialement,
