### ISSUE TITLE
rights not updated after creating a field for a generic object

### ISSUE THREAD

**Issue by btry** [TECLIB/genericobject#52]
Add a dropdown type field (category) for a generic object, and try to populate the dropdown in configuration > dropdowns > category (mygenericobject)

the + sign is grayed.

Must logout and login again before adding items.

**Comment by btry** [comment]
Menu of GLPI is built when loading a profile (login, change profile). The menu is cached and needs a rebuild when a field is added to an generic object. 

The fix is ready to test.

**Comment by blerohellec** [comment]
OK. It works fine.
