### ISSUE TITLE
GLPI 0.90: Erreur 404 sur Liste des matériels

### ISSUE THREAD

**Issue by jmreymond** [TECLIB/genericobject#56]
Lorsqu'on associe à un contrat beaucoup d'éléments de type genericobjects, on voit alors apparaître  une entrée Liste des matériels plutôt que l'énumération, ce qui est une bonne chose.
En cliquant sur le lien, on obtient une erreur 404
http://glpi.aapca.net/plugins/genericobject/front/planeur.php?order=ASC&is_deleted=0&reset=reset&start=0&sort=80&criteria[0][value]=%24%24%24%242&criteria[0][searchtype]=contains&criteria[0][field]=29

**Comment by Manu1400** [comment]
Le fichier planeur.php n'existe pas d'où une 404 pour l'URL : http://glpi.aapca.net/plugins/genericobject/front/planeur.php

Il semble qu'il s'agit ici d'un ancien objet genericobjet.

**Comment by jmreymond** [comment]
l'objet existe bien mais l'URL semble étonnante. Toutes les autres URL sont de la forme 
http://glpi.aapca.net/plugins/genericobject/front/object.form.php?itemtype=PluginGenericobjectPlaneur&id=3

**Comment by jmreymond** [comment]
Si je change la taille de la liste d'affichage par exemple à 100 éléments, je n'ai plus le message Liste des matériels mais le détail de chaque élément et je n'ai aucun soucis pour voir chaque élément, ce qui semble indiquer qu'il existe bien

**Comment by Manu1400** [comment]
Pouvez vous joindre une (ou plusieurs) capture d'écran ?

**Comment by jmreymond** [comment]
Un contrat avec un affichage du nombre d’éléments fixé à 50
![capture du 2015-10-14 09 32 20](https://cloud.githubusercontent.com/assets/8809413/10477489/da1a91c4-7256-11e5-9e59-6153a3026d95.png)

Un contrat avec un affichage du nombre d’éléments fixé à 20
![capture du 2015-10-14 09 33 20](https://cloud.githubusercontent.com/assets/8809413/10477500/f02f42ac-7256-11e5-87de-8e2d9c3e2a08.png)

Et ce qui arrive quand on clique sur la Liste des matériels
![capture du 2015-10-14 09 34 14](https://cloud.githubusercontent.com/assets/8809413/10477507/fc9f46fe-7256-11e5-9751-253462a80704.png)

**Comment by Manu1400** [comment]
Merci beaucoup pour les captures d'écran.

Il s'agit d'un bug GLPI et d'un bug du plugin genericobject.

Il me parait souhaitable d'attendre la correction du bug GLPI https://github.com/glpi-project/glpi/issues/174 avant d'évoquer une correction ici.

**Comment by jmreymond** [comment]
j'avais trouvé que le bug se situait dans inc/toolbox.class.php pour 
la fonction getItemTypeSearchURL mais effectivement, derrière arrivait le problème des paramètres de tri.

**Comment by jmreymond** [comment]
vérification faite qu'en créant 6 imprimantes et en mettant la limite d'affichage à 5, on a bien Liste des matériels mais pas d'erreur 404 lors du clic sur cet item

**Comment by Manu1400** [comment]
Un correctif a été ajouté dans le code de GLPI (pour la future version 0.90.1)

https://github.com/glpi-project/glpi/commit/5ed96ca689e3086770204d058747388a4914d7f3

**Comment by jmreymond** [comment]
Nettement meilleur car cela ne provoque plus une erreur 404 mais il y a un $$$$2 qui se promène dans la liste des paramètres

http://aapca.ckr-solutions.com/plugins/genericobject/front/object.php?itemtype=PluginGenericobjectBatiment?order=ASC&is_deleted=0&reset=reset&start=0&sort=80&criteria[0][value]=%24%24%24%242&criteria[0][searchtype]=contains&criteria[0][field]=29

![capture du 2015-10-15 15 03 42](https://cloud.githubusercontent.com/assets/8809413/10514435/f543437c-734d-11e5-91e3-13344bc423d7.png)

**Comment by wawax** [comment]
should be fixed in commit https://github.com/glpi-project/glpi/commit/ec6a5bc832cc7370a36a43c7254a5fad1c3bb4e6

**Comment by jmreymond** [comment]
c'est parfait
