### ISSUE TITLE
Troubles with reservations

### ISSUE THREAD

**Issue by marcogaio** [TECLIB/genericobject#57]
I'm using GLPI 0.85.5,  genericobject 0.85-1.0.
I use that plugin mostly to create a 'room' object to use as a reservation purpose.

After upgrading to GLPI 0.85, i've lost, for 'post-only' users, the ability to reserve rooms. And in a strange way.

For example, if i go to Utility -> Reservation, rooms does not appear.
But if i select another reservable item, and then i select the 'Show all' button on the top, i can see reservation on the rooms, and if i select one, i can jump to the room calendar and make reservation flawlessy.

So seems to me that the only think that missed is the reservable room genericobjects on the main reservation page.
Note that for 'super-admin' users, all items are reservable, they desappear only for non-'super-admin' users. ACL (Administration -> Profiles) seems OK.

I've looked at log, but no errors get printed on.

Thanks.

**Comment by marcogaio** [comment]
Some feedback on that? There's something i can do to help?

Please, provide me feedback... thanks.

**Comment by btry** [comment]
I updated the plugin to solve some clean up issues with reservations (see #9). Maybe it will somehow help for your issue. 

Other fixes coming soon.

**Comment by btry** [comment]
Hi

I confirm your issue. With the self service profile, I cannot reserve and view a generic object in reservations.

**Comment by btry** [comment]
Please try this fix

**Comment by marcogaio** [comment]
Sorry, yesterday i've had no time to look at #9.

But... your fix work PERFECTLY! Thanks!!!

**Comment by btry** [comment]
Thank you for your feedback. Have fun with the plugin.
