### ISSUE TITLE
Tools > Reservations crashes when User is part of the view

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/genericobject#7]
In Tools > Reservations, a list of objects allowed to be reserved is presented (all item types including objects generated via genericobject).
If User is part of the view, and the genericobject doesn't include User among its fields -> crash (see sql-errors.log).
Because GLPI generates a SQL request (union) and column users_id is not present in the table of the genericobject.

UNION SELECT \'glpi\' AS currentuser,
                        `glpi_reservationitems`.`is_active` AS ACTIVE, `glpi_reservationitems`.`entities_id`, `glpi_reservationitems`.`is_recursive`,  `glpi_plugin_genericobject_salles`.`name` AS ITEM_0,
                        `glpi_plugin_genericobject_salles`.`id` AS ITEM_0_2,
                        `glpi_entities`.`completename` AS ITEM_1,
              `glpi_reservationitems`.`comment` AS ITEM_2,
              `glpi_locations`.`completename` AS ITEM_3,
              `glpi_reservationitems`.`is_active` AS ITEM_4,
              `glpi_plugin_genericobject_salles`.`id` AS id , \'PluginGenericobjectSalle\' AS TYPE,
                                      `glpi_reservationitems`.`id` AS refID, 
                                      `glpi_plugin_genericobject_salles`.`entities_id` AS ENTITY  FROM `glpi_reservationitems`
                              INNER JOIN `glpi_plugin_genericobject_salles`
                                 ON (`glpi_reservationitems`.`items_id`=`glpi_plugin_genericobject_salles`.`id`
                                     AND `glpi_reservationitems`.`itemtype` = \'PluginGenericobjectSalle\')LEFT JOIN `glpi_entities` 
                                          ON (`glpi_plugin_genericobject_salles`.`entities_id` = `glpi_entities`.`id`
                                              )LEFT JOIN `glpi_locations` 
                                          ON (`glpi_plugin_genericobject_salles`.`locations_id` = `glpi_locations`.`id`
                                              )LEFT JOIN `glpi_users` 
                                          ON (`glpi_plugin_genericobject_salles`.`users_id` = `glpi_users`.`id`
                                              )LEFT JOIN `glpi_groups` 
                                          ON (`glpi_plugin_genericobject_salles`.`groups_id` = `glpi_groups`.`id`
                                              )LEFT JOIN `glpi_manufacturers` 
                                          ON (`glpi_plugin_genericobject_salles`.`manufacturers_id` = `glpi_manufacturers`.`id`
                                              )LEFT JOIN `glpi_users`  AS glpi_users_users_id_tech
                                          ON (`glpi_plugin_genericobject_salles`.`users_id_tech` = `glpi_users_users_id_tech`.`id`
                                              ) WHERE  `glpi_reservationitems`.`is_deleted` = \'0\'  AND   (  1 )   AND (  (    `glpi_reservationitems`.`comment`  LIKE \'%salle%\'    OR  `glpi_reservationitems`.`is_active`  LIKE \'%salle%\'    OR  `glpi_plugin_genericobject_salles`.`name`  LIKE \'%salle%\'    OR  `glpi_plugin_genericobject_salles`.`id`  LIKE \'%salle%\'    OR  `glpi_locations`.`completename`  LIKE \'%salle%\'    OR  `glpi_locations`.`building`  LIKE \'%salle%\'    OR  `glpi_locations`.`room`  LIKE \'%salle%\'    OR  `glpi_locations`.`comment`  LIKE \'%salle%\'    OR  `glpi_plugin_genericobject_salles`.`comment`  LIKE \'%salle%\'   OR  (((`glpi_users`.`realname`   LIKE \'%salle%\' 
                            OR `glpi_users`.`firstname`   LIKE \'%salle%\' 
                            OR `glpi_users`.`name`   LIKE \'%salle%\' 
                            OR CONCAT(`glpi_users`.`realname`, \' \', `glpi_users`.`firstname`)   LIKE \'%salle%\'  )
                            ) )  OR  `glpi_groups`.`completename`  LIKE \'%salle%\'    OR  `glpi_plugin_genericobject_salles`.`date_mod`  LIKE \'%salle%\'    OR  `glpi_manufacturers`.`name`  LIKE \'%salle%\'   OR  (((`glpi_users_users_id_tech`.`realname`   LIKE \'%salle%\' 
                            OR `glpi_users_users_id_tech`.`firstname`   LIKE \'%salle%\' 
                            OR `glpi_users_users_id_tech`.`name`   LIKE \'%salle%\' 
                            OR CONCAT(`glpi_users_users_id_tech`.`realname`, \' \', `glpi_users_users_id_tech`.`firstname`)   LIKE \'%salle%\'  )
                            ) )  OR  `glpi_entities`.`completename`  LIKE \'%salle%\'   )  ) ORDER BY ITEM_0 ASC 
Error: Unknown column 'glpi_plugin_genericobject_salles.users_id' in 'on clause'
Backtrace :
/var/www/glpiOLD/inc/search.class.php&nbsp;:790		DBmysql->query()
/var/www/glpiOLD/inc/search.class.php&nbsp;:63		Search::showList()
/var/www/glpiOLD/front/reservationitem.php&nbsp;:48		Search::show()
/var/www/glpiOLD/front/reservationitem.php

**Comment by wawax** [comment]
Please test again with the latest plugin's commits

**Comment by blerohellec** [comment]
Much better.
To be consistent, you should also prohibit to delete the User field when 'use reservations' is enabled. Or automatically disable 'use reservations'.

**Comment by wawax** [comment]
Please the again with my last commit

**Comment by blerohellec** [comment]
Perfect. You can close. Thx
