### ISSUE TITLE
inc/includes.php is missing from the repository

### ISSUE THREAD

**Issue by tech62** [TECLIB/genericobject#71]
GLPI Version 0.90.1
How ? : 

When you want adding a new family when you add a new object , but It's a random bug, i've an error the first time when i created the first new object.

The error persist when you have this url : http://yourserver/glpi/plugins/genericobject/front/typefamily.php

------------

Warning: include(../inc/includes.php): failed to open stream: No such file or directory in /var/www/glpi/plugins/genericobject/front/typefamily.php on line 28

Warning: include(): Failed opening '../inc/includes.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/glpi/plugins/genericobject/front/typefamily.php on line 28

Fatal error: Class 'PluginGenericobjectTypeFamily' not found in /var/www/glpi/plugins/genericobject/front/typefamily.php on line 30

**Comment by dethegeek** [comment]
I guess you're impacted by an already fixed bug. Can you try with the latest revision from the master branch ?

**Comment by tech62** [comment]
It's the latest version, downloaded from https://github.com/TECLIB/genericobject/releases

**Comment by dethegeek** [comment]
I did the fix later, then it is not in this release. 

You may compare your version if front/typefamily.php with this commit https://github.com/TECLIB/genericobject/commit/dd1dc0ba32354363e4e16837bfef422cde9d145a

**Comment by tech62** [comment]
i've this in the typefamily.php : 
include ('../inc/includes.php');

$dropdown = new PluginGenericobjectTypeFamily();
include (GLPI_ROOT . "/front/dropdown.common.php");

i've re-downloaded the archive from https://github.com/TECLIB/genericobject/releases/download/0.85-1.0/genericobject-0.85-1.0.zip

and i've the same code in the file

**Comment by dethegeek** [comment]
The latest code is available here : https://github.com/TECLIB/genericobject/archive/master.zip

This link let you download the not-yet-released version.

Test it before a production use.

**Comment by tech62** [comment]
It's done , thanks !
