### ISSUE TITLE
Clean-up not complete when genericobjet is reservable

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/genericobject#9]
Create a genericobject where 'Use Reservations'=yes
Create an instance and authorize reservations. It creates a record in table glpi_reservationitems.
Delete permanently the genericobject instance -> glpi_reservationitems is not cleaned.

Clean-up has to be done also by deleting the genericobject type, and at plugin desinstalation time.
Check also that reservations made on this instance are to be cleaned (table glpi_reservations).

With the same logic, check clean-up of links with contracts, documents, etc

**Comment by wawax** [comment]
done in my last commits

**Comment by blerohellec** [comment]
Cleanup is not yet done when one deletes the generic object type. Records are still there in tables glpi_reservationitems and glpi_reservations.

Furthermore, it is responsible for an error in Reservation tab of Tools > Reservations
- the list of reservable items is empty
- click on 'find a free item in a specific period' leads to "Fatal error: Class 'PluginGenericobjectVoiture' not found in /var/www/glpi085/inc/reservationitem.class.php on line 422" (on screen only)

**Comment by wawax** [comment]
Thanks Benoit,

I'm going to test it again

**Comment by blerohellec** [comment]
Still to be solved

**Comment by geekson** [comment]
Hi,
I'm having the same problem as the one described above. Reservation items are not visible anymore.

glpi 0.90 generic object plugin 0.85-1.0

Please help!

**Comment by btry** [comment]
Hi,

With the master branch : 
- I created a new type (with reservations ticked)
- I created an item from this new type
- I added a reservation on this type
- I deleted the itemtype

I'm still able to navigate through reservation. (list of reservable items, and view a calendar for a remaining item)

@geekson : Did you try the latest revision of the plugin ? Can you provide a screenshot if the bug still occurs, and share relevants parts of php_errors.log and sql_errors.log, if any ?

@blerohellec : 
glpi_reservationitems =>  my deleted item is still here
glpi_reservations => the reservation I added is still here

**Comment by geekson** [comment]
Hello,
attached files show the error. 
version is:  Objects management	0.85-1.0	Teclib' & siprossii
downloaded 10 days ago


![no reservable item shown](https://cloud.githubusercontent.com/assets/15198277/10600873/f2b2d9f6-770d-11e5-9e3c-c7685bc57b59.PNG)

![whatever reservation](https://cloud.githubusercontent.com/assets/15198277/10600876/f53b0b08-770d-11e5-9d64-6749ea3550fc.PNG)

10-09 18:01:10 [2@SPOOL-FR100100V]
  From MassiveAction::__construct() in C:\wamp\www\glpi\inc\massiveaction.class.php line 267
  Implementation error ! 
2015-10-09 18:02:44 [2@SPOOL-FR100100V]
  *** PHP Notice(8): Undefined index: itemtype
  Backtrace :
  inc\massiveaction.class.php:1182                   
  inc\massiveaction.class.php:991                    MassiveAction::processMassiveActionsForOneItemtype()
  inc\massiveaction.class.php:970                    MassiveAction->processForSeveralItemtypes()
  front\massiveaction.php:62                         MassiveAction->process()
2015-10-09 18:02:44 [2@SPOOL-FR100100V]
  *** PHP Notice(8): Undefined index: itemtype
  Backtrace :
  inc\massiveaction.class.php:1186                   
  inc\massiveaction.class.php:991                    MassiveAction::processMassiveActionsForOneItemtype()
  inc\massiveaction.class.php:970                    MassiveAction->processForSeveralItemtypes()
  front\massiveaction.php:62                         MassiveAction->process()
2015-10-09 18:03:05 [2@SPOOL-FR100100V]
  *** PHP Notice(8): Undefined index: Test
  Backtrace :
  plugins\fields\inc\container.class.php:134         
  inc\search.class.php:4869                          PluginFieldsContainer::getSpecificValueToDisplay()
  inc\search.class.php:1107                          Search::giveItem()
  inc\search.class.php:98                            Search::constructDatas()
  inc\search.class.php:81                            Search::showList()
  plugins\fields\front\container.php:10              Search::show()
2015-10-09 18:03:10 [2@SPOOL-FR100100V]
  *** PHP Notice(8): Undefined index: Test
  Backtrace :
  plugins\fields\inc\container.class.php:301         
  inc\commonglpi.class.php:460                       PluginFieldsContainer->showForm()
  ajax\common.tabs.php:91                            CommonGLPI::displayStandardTab()
2015-10-09 18:06:41 [2@SPOOL-FR100100V]
  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 13
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\profile.class.php:260    _log()
  plugins\genericobject\inc\profile.class.php:240    PluginGenericobjectProfile::profileExists()
  plugins\genericobject\inc\profile.class.php:440    PluginGenericobjectProfile::createFirstAccess()
  plugins\genericobject\hook.php:118                 PluginGenericobjectProfile::install()
  inc\plugin.class.php:643                           plugin_genericobject_install()
  front\plugin.form.php:49                           Plugin->install()
2015-10-09 18:08:57 [2@SPOOL-FR100100V]
  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 13
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\profile.class.php:337    _log()
  plugins\genericobject\inc\type.class.php:722       PluginGenericobjectProfile::installRights()
  plugins\genericobject\inc\type.class.php:206       PluginGenericobjectType::addNewObject()
  inc\commondbtm.class.php:832                       PluginGenericobjectType->post_addItem()
  plugins\genericobject\front\type.form.php:49       CommonDBTM->add()
2015-10-09 18:08:57 [2@SPOOL-FR100100V]
  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 13
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\profile.class.php:337    _log()
  plugins\genericobject\inc\type.class.php:722       PluginGenericobjectProfile::installRights()
  plugins\genericobject\inc\type.class.php:206       PluginGenericobjectType::addNewObject()
  inc\commondbtm.class.php:832                       PluginGenericobjectType->post_addItem()
  plugins\genericobject\front\type.form.php:49       CommonDBTM->add()
2015-10-09 18:08:58 [2@SPOOL-FR100100V]
  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 13
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\hook.php:49                  _log()
  :                                                  plugin_genericobject_getDropdown()
  inc\plugin.class.php:1166                          call_user_func()
  inc\plugin.class.php:1181                          Plugin::doOneHook()
  inc\dropdown.class.php:858                         Plugin::getDropdowns()
  inc\commondropdown.class.php:108                   Dropdown::getStandardDropdownItemTypes()
  inc\html.class.php:1282                            CommonDropdown::getMenuContent()
  plugins\genericobject\front\type.form.php:74       Html::header()
2015-10-09 18:09:31 [2@SPOOL-FR100100V]
  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 13
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\field.class.php:311      _log()
  plugins\genericobject\inc\type.class.php:769       PluginGenericobjectField::addNewField()
  plugins\genericobject\inc\type.class.php:229       PluginGenericobjectType->checkNecessaryFieldsUpdate()
  inc\commondbtm.class.php:1144                      PluginGenericobjectType->post_updateItem()
  plugins\genericobject\front\type.form.php:57       CommonDBTM->update()
2015-10-09 18:09:31 [2@SPOOL-FR100100V]
  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 13
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\field.class.php:311      _log()
  plugins\genericobject\inc\type.class.php:770       PluginGenericobjectField::addNewField()
  plugins\genericobject\inc\type.class.php:229       PluginGenericobjectType->checkNecessaryFieldsUpdate()
  inc\commondbtm.class.php:1144                      PluginGenericobjectType->post_updateItem()
  plugins\genericobject\front\type.form.php:57       CommonDBTM->update()
2015-10-09 18:09:31 [2@SPOOL-FR100100V]
  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 13
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\field.class.php:311      _log()
  plugins\genericobject\inc\type.class.php:771       PluginGenericobjectField::addNewField()
  plugins\genericobject\inc\type.class.php:229       PluginGenericobjectType->checkNecessaryFieldsUpdate()
  inc\commondbtm.class.php:1144                      PluginGenericobjectType->post_updateItem()
  plugins\genericobject\front\type.form.php:57       CommonDBTM->update()
2015-10-09 18:09:31 [2@SPOOL-FR100100V]
  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 13
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\field.class.php:311      _log()
  plugins\genericobject\inc\type.class.php:772       PluginGenericobjectField::addNewField()
  plugins\genericobject\inc\type.class.php:229       PluginGenericobjectType->checkNecessaryFieldsUpdate()
  inc\commondbtm.class.php:1144                      PluginGenericobjectType->post_updateItem()
  plugins\genericobject\front\type.form.php:57       CommonDBTM->update()
2015-10-09 18:09:31 [2@SPOOL-FR100100V]
  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 13
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\field.class.php:311      _log()
  plugins\genericobject\inc\type.class.php:773       PluginGenericobjectField::addNewField()
  plugins\genericobject\inc\type.class.php:229   

sql_error log:

Error: Erreur de syntaxe près de ') 
      AND glpi_tickets.entities_id IN (0,0)' à la ligne 5
  Backtrace :
  ...p\www\glpi\plugins\dashboard\front\main.php:271 
2015-10-13 17:49:01 [6@SPOOL-FR100100V]
  *** MySQL query error:
  SQL: SELECT COUNT(glpi_tickets.id) as total        
      FROM glpi_tickets
      LEFT JOIN glpi_entities ON glpi_tickets.entities_id = glpi_entities.id
      WHERE glpi_tickets.is_deleted = \'0\' 
      AND DATE_FORMAT( glpi_tickets.date, \'%Y\' ) IN () 
      AND glpi_tickets.entities_id IN (0,0) 
  Error: Erreur de syntaxe près de ') 
      AND glpi_tickets.entities_id IN (0,0)' à la ligne 5
  Backtrace :
  ...p\www\glpi\plugins\dashboard\front\main.php:271 
2015-10-13 17:49:39 [2@SPOOL-FR100100V]
  *** MySQL query error:
  SQL: SELECT COUNT(glpi_tickets.id) as total        
      FROM glpi_tickets
      LEFT JOIN glpi_entities ON glpi_tickets.entities_id = glpi_entities.id
      WHERE glpi_tickets.is_deleted = \'0\' 
      AND DATE_FORMAT( glpi_tickets.date, \'%Y\' ) IN () 
      AND glpi_tickets.entities_id IN (0,0)

hope that help....

**Comment by geekson** [comment]
This part might be more relevant:
  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 13
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\hook.php:49                  _log()
  :                                                  plugin_genericobject_getDropdown()
  inc\plugin.class.php:1166                          call_user_func()
  inc\plugin.class.php:1181                          Plugin::doOneHook()
  inc\dropdown.class.php:858                         Plugin::getDropdowns()
  inc\commondropdown.class.php:108                   Dropdown::getStandardDropdownItemTypes()
  inc\html.class.php:1282                            CommonDropdown::getMenuContent()
  front\central.php:72                               Html::header()

**Comment by geekson** [comment]
And this one from sql_errorlog is probably more relevant too:

  SQL: SELECT COUNT(glpi_tickets.id) as total        
      FROM glpi_tickets
      LEFT JOIN glpi_entities ON glpi_tickets.entities_id = glpi_entities.id
      WHERE glpi_tickets.is_deleted = \'0\' 
      AND DATE_FORMAT( glpi_tickets.date, \'%Y\' ) IN () 
      AND glpi_tickets.entities_id IN (0,0) 
  Error: Erreur de syntaxe près de ') 
      AND glpi_tickets.entities_id IN (0,0)' à la ligne 5
  Backtrace :
  ...p\www\glpi\plugins\dashboard\front\main.php:271 
2015-10-13 17:49:39 [2@SPOOL-FR100100V]
  *** MySQL query error:
  SQL: SELECT COUNT(glpi_tickets.id) as total        
      FROM glpi_tickets
      LEFT JOIN glpi_entities ON glpi_tickets.entities_id = glpi_entities.id
      WHERE glpi_tickets.is_deleted = \'0\' 
      AND DATE_FORMAT( glpi_tickets.date, \'%Y\' ) IN () 
      AND glpi_tickets.entities_id IN (0,0) 
  Error: Erreur de syntaxe près de ') 
      AND glpi_tickets.entities_id IN (0,0)' à la ligne 5
  Backtrace :
  ...p\www\glpi\plugins\dashboard\front\main.php:271

**Comment by btry** [comment]
I guess you got the second screenshot by clicking on the administration" tab. Am I right ?

**Comment by geekson** [comment]
Nope, you get the second screenshot by searching any date. Which mean there is no reservation possible.
Anything I can do?

**Comment by btry** [comment]
Reservation tables now cleaned up. Does it help to solve your issue ?

**Comment by geekson** [comment]
Sorry, what I am supposed to do here?

**Comment by btry** [comment]
Assuming you got a qualification setup of GLPI (using a copy of your production database) : 
- reset the testing database with your latest backup
- download an updated copy of genericobjects from the master branch ( https://github.com/TECLIB/genericobject )
- decompress the archive and install the files as usual (double check the name of the folder containing setup.php : it must be genericobject
- overwrite the previous version of the plugin with new one
- logout from GLPI and login again
- check the plugin runs as expected

**Comment by geekson** [comment]
I'm still unable to make a reservation. Even after a reset, the plugin doesn't seems to clean as expected.

**Comment by geekson** [comment]
2015-10-20 15:57:38 [2@SPOOL-FR100100V]
  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 13
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\profile.class.php:260    _log()
  plugins\genericobject\inc\profile.class.php:240    PluginGenericobjectProfile::profileExists()
  plugins\genericobject\inc\profile.class.php:440    PluginGenericobjectProfile::createFirstAccess()
  plugins\genericobject\hook.php:118                 PluginGenericobjectProfile::install()
  inc\plugin.class.php:643                           plugin_genericobject_install()
  front\plugin.form.php:49                           Plugin->install()

**Comment by btry** [comment]
The clean up occurs when you delete a type from the plugin. If your backup contains reservation data for an already deleted type, the error will persist.  I guess this is your case.

Can you use a database administration tool like phpmyadmin to check the tables glpi_reservations and glpi_reservationitems ? 

- glpi_reservationitems must not contain entries for a deleted type
- all reservationitems_id values in table glpi_reservations must match an id from glpi_reservationitems

**Comment by btry** [comment]
The warning related to preg_replace seems not related, but I'll fix it soon.

**Comment by geekson** [comment]
Congrats!

glpi_reservationitems must not contain entries for a deleted type
You saved my day ! 
:dancers: Thanks a lot Mister

**Comment by btry** [comment]
;) 

Now I need to know if the problem no longer occurs when one delete a type. This is the purpose of the patch.

@blerohellec : I'll investigate soon for other cleanups

**Comment by btry** [comment]
@blerohellec : Added cleanup on table glpi_contracts_items . This fix the unability to link a contract to an item ig a generic type has been deleted without removing its relations to contracts.

Waiting for your feedback

**Comment by blerohellec** [comment]
Cleanup of table glpi_contracts_items OK at both GO instance deletion, and GO type deletion.
Thx
